name: dlabs-master-deploy

on: # push events on, and pull requests against, master branch
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  dlabs-master-deploy-workflow:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm install, project linter and test suite
        run: |
          npm install
          npm run lint
          npm test -- --coverage -u
      - name: Send passing test suite's coverage to coveralls
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.info'
      - name: Build production folder
        run: |
          npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          CI: false
