name: dlabs-latest-release

on: # 1st of every month, at 5pm PST
  schedule:
    - cron: '59 23 10 */1 *' # using 10th day for initial testing

jobs:
  dlabs-latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          check-version: true
          token: ${{ secrets.NPM_TOKEN }}
